### ISSUE TITLE
Do you plan to upstream this?

### ISSUE THREAD

**Issue by probonopd** [NorwegianRockCat/FreeBSD-my-ports#2]
Thanks @NorwegianRockCat for making this repository. I came here while searching for a port of `x11/gtk-app-menu`.

Do you plan to submit this to the official ports tree?

**Comment by NorwegianRockCat** [comment]
I’ve submitted a [bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236155). I hope that it gets committed soon. You can watch that and I’ll ask nicely to if they could look again.

**Comment by NorwegianRockCat** [comment]
Successfully added into the [ports tree](https://svnweb.freebsd.org/changeset/ports/553251).

**Comment by probonopd** [comment]
Thank you very much @NorwegianRockCat. Very useful :+1:
